version: "3.7"
services: 
    web:
        image: nginx
        build: 
            context: ./nginx/
        restart: always
        ports: 
            - 80:80
        networks: 
            - expenses-network
        depends_on: 
            - expenses-react
            - expenses-api
        
    postgres:
        image: postgres
        environment:
            POSTGRES_PASSWORD: postgres
        ports: 
            - '5432:5432'
        volumes: 
            - expenses_db:/var/lib/postgresql/data
        networks: 
            - expenses-network

    expenses-api:
        build:
            context: ./server/
        environment:
            DB_SCHEMA: postgres
            DB_USERNAME: postgres
            DB_PASSWORD: postgres
            DB_HOST: postgres
        volumes:
            - ./server/:/home/node/app/server
        depends_on: 
            - postgres
        ports: 
            - '3000:3000'
        networks:
            - expenses-network

    expenses-react:
        build:
            context: ./client/
        volumes:
            - ./client/:/home/node/app/client
            - /home/node/app/client/node_modules
        ports:
            - 3001:3001
        environment: 
            - CHOKIDAR_USEPOLLING=true
        depends_on: 
            - expenses-api
        stdin_open: true
        networks: 
            - expenses-network
            
volumes: 
    expenses_db:

networks: 
    expenses-network: