version: "3.7"
services: 
    postgres:
        image: postgres
        environment:
            POSTGRES_PASSWORD: postgres
        ports: 
            - '5432:5432'
        volumes: 
            - expenses_db:/var/lib/postgresql/data

    expenses-api:
        build:
            context: ./server/
        environment:
            DB_SCHEMA: postgres
            DB_USERNAME: postgres
            DB_PASSWORD: postgres
            DB_HOST: postgres
        volumes:
            - ./server/:/home/node/app/server
        depends_on: 
            - postgres
        ports: 
            - '3000:3000'

    expenses-react:
        build:
            context: ./client/
        volumes:
            - ./client/:/home/node/app/client
            - /home/node/app/client/node_modules
        ports:
            - 3001:3001
        environment: 
            - CHOKIDAR_USEPOLLING=true
        depends_on: 
            - expenses-api
        stdin_open: true
            
volumes: 
    expenses_db: